apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mgd7tc7ae-python 
  janus-idp.io/tekton: mgd7tc7ae-python
  backstage.io/kubernetes-id: mgd7tc7ae-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mgd7tc7ae-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml